### ISSUE TITLE
コンテスト情報を取得した後にm3-config.tomlに書き出し

### ISSUE THREAD

**Issue by kryInit** [kryInit/marathon-matches-manager#9]
related to #8 
多分一番簡単
feature/new/m3-config_#9的なbranchを作成してやる
こんな感じで（適当か？
```toml
[contest]
url = "https://atcoder.jp/contests/ahc018"
name = "RECRUIT 日本橋ハーフマラソン 2023冬（AtCoder Heuristic Contest 018)"
sub_name = "ahc018"
start_time = "2023-02-18 12:00:00+0900"
time_limit = "199:00"
is_rated = "All"
```

**Comment by kryInit** [comment]
`lib/new/generate_template.py`で`related_contest`が取れているので`lib/new/generate_m3_config.py`でその内容を見て生成する感じで
他の情報も書き出してくれると嬉しみ
```toml
[project]
name = "ahc018"

[environment]
default_working_directory = "${PROJECT_ROOT_PATH}/workspace"

[contest]
url = "https://atcoder.jp/contests/ahc018"
name = "RECRUIT 日本橋ハーフマラソン 2023冬（AtCoder Heuristic Contest 018)"
sub_name = "ahc018"
start_time = "2023-02-18 12:00:00+0900"
time_limit = "199:00"
is_rated = "All"
```
